import {DEFAULT_SETTINGS,LABELS} from './estimate-config.js';
import {appState,createDraft} from './state.js';
import {storage,validBackup} from './storage.js';
import {calculateEstimate} from './estimate.js';
import {validateStep} from './validation.js';
import {buildMailto,caseText,copyText} from './export.js';
import {clone,debounce,download,uid} from './utils.js';
import {settingsFromForm,resetSettings} from './settings.js';
import {customerFields,renderDetail,renderHistory,renderHome,renderSettings,renderStep} from './ui.js';
import {hashPasscode,verifyPasscode} from './security.js';

const main=document.querySelector('#main'),progress=document.querySelector('#progressWrap'),headerCompany=document.querySelector('#headerCompany');
let settings=storage.getSettings(DEFAULT_SETTINGS);let cases=storage.getCases().map(normalizeCase);
const draftSaved=debounce(()=>{if(appState.step>0&&appState.step<8)try{storage.saveDraft(appState.draft)}catch(e){toast(e.message)}},200);
applySettings();renderHomeScreen();

document.querySelector('#homeButton').addEventListener('click',()=>goHome());
document.querySelector('#settingsButton').addEventListener('click',requestSettingsAccess);
main.addEventListener('click',handleClick);main.addEventListener('change',handleChange);main.addEventListener('input',handleInput);

function render(){applySettings();progress.hidden=appState.screen!=='wizard'||appState.step===8;document.body.classList.toggle('has-progress',!progress.hidden);if(appState.screen==='home')main.innerHTML=renderHome(settings,!!storage.getDraft());if(appState.screen==='wizard'){main.innerHTML=renderStep(appState.step,appState.draft,settings,appState.mediaFiles);updateProgress()}if(appState.screen==='history')main.innerHTML=renderHistory(cases,settings);if(appState.screen==='settings'){main.innerHTML=renderSettings(settings);enhanceSettings()}if(appState.screen==='detail')main.innerHTML=renderDetail(appState.draft,settings);main.focus({preventScroll:true});scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}
function renderHomeScreen(){appState.screen='home';appState.step=0;render()}
function goHome(){if(appState.screen==='wizard'&&appState.step>0&&appState.step<8)syncForm();renderHomeScreen()}
function applySettings(){document.documentElement.style.setProperty('--color-primary',settings.app.mainColor);document.documentElement.style.setProperty('--main',settings.app.mainColor);document.documentElement.style.setProperty('--color-accent',settings.app.accentColor);document.documentElement.style.setProperty('--accent',settings.app.accentColor);headerCompany.textContent=settings.company.name;document.title=settings.app.name;const mark=document.querySelector('#logoMark');mark.replaceChildren();if(settings.company.logoDataUrl?.startsWith('data:image/')){const img=document.createElement('img');img.className='logo-image';img.alt='';img.src=settings.company.logoDataUrl;mark.append(img)}else mark.textContent='窓'}
function updateProgress(){const n=Math.min(appState.step,8);document.querySelector('#stepLabel').textContent=`STEP ${n} / 8`;document.querySelector('#stepName').textContent=['','依頼者情報','症状選択','写真・動画','現場情報','排煙窓の問診','概算・料金','内容確認','保存完了'][n];document.querySelector('#progressBar').style.width=`${n/8*100}%`;const bar=document.querySelector('[role=progressbar]');bar.setAttribute('aria-valuenow',n);bar.setAttribute('aria-valuetext',`8段階中${n}段階、${document.querySelector('#stepName').textContent}`)}
function start(draft=null){appState.draft=normalizeCase(draft||createDraft());appState.mediaFiles=[];appState.editingId=draft?.id||null;appState.screen='wizard';appState.step=1;render();draftSaved()}
async function handleClick(e){const action=e.target.closest('[data-action]')?.dataset.action;if(action){if(action==='start')start();if(action==='resume'){const d=storage.getDraft();start(d||null)}if(action==='home')goHome();if(action==='history'){cases=storage.getCases().map(normalizeCase);appState.screen='history';render()}if(action==='help')showHelp();if(action==='back')previous();if(action==='next')next();if(action==='clear-media')clearMedia();if(action==='copy-current')doCopy(appState.draft);if(action==='send-email')sendEmail(appState.draft);if(action==='share-media')await shareMedia(appState.draft);if(action==='print')printCurrentView();if(action==='export')exportBackup();if(action==='delete-all')deleteAll();if(action==='save-settings')await saveSettings();if(action==='reset-settings')resetAllSettings()}const rm=e.target.closest('[data-remove-media]');if(rm)removeMedia(Number(rm.dataset.removeMedia));const edit=e.target.closest('[data-edit-step]');if(edit){appState.screen='wizard';appState.step=Number(edit.dataset.editStep);render()}const ca=e.target.closest('[data-case-action]');if(ca)await caseAction(ca.dataset.caseAction,ca.dataset.id)}
function handleChange(e){if(e.target.id==='mediaInput')addMedia([...e.target.files]);if(e.target.id==='importInput')importBackup(e.target.files[0]);if(e.target.id==='companyLogo')loadLogo(e.target.files[0]);if(e.target.name==='customerType'){syncForm();appState.draft.customerType=e.target.value;document.querySelector('#customerFields').innerHTML=customerFields(appState.draft);draftSaved()}if(e.target.id==='agreed'){appState.draft.inspectionFee.agreed=e.target.checked;appState.draft.inspectionFee.agreedAt=e.target.checked?new Date().toISOString():null;draftSaved()}}
function handleInput(){if(appState.screen==='wizard'){syncForm();draftSaved()}}
function syncForm(){const form=document.querySelector('#stepForm');if(!form)return;const symptomInputs=[...form.querySelectorAll('[name="diagnosis.symptoms"]')];if(symptomInputs.length){const values=symptomInputs.filter(input=>input.checked).map(input=>input.value);appState.draft.diagnosis.symptoms=values;appState.draft.diagnosis.symptom=values[0]||''}for(const [name,value] of new FormData(form)){if(name==='diagnosis.symptoms')continue;setPath(appState.draft,name,value)}}
function setPath(obj,path,value){const keys=path.split('.');let o=obj;while(keys.length>1){const k=keys.shift();o[k]??={};o=o[k]}o[keys[0]]=value}
function previous(){syncForm();if(appState.step===1){renderHomeScreen();return}appState.step--;render();draftSaved()}
function next(){syncForm();const errors=validateStep(appState.step,appState.draft);if(Object.keys(errors).length){showErrors(errors);return}if(appState.step===5){appState.draft.estimate=calculateEstimate(appState.draft,settings);Object.assign(appState.draft.inspectionFee,{amount:settings.inspection.fee,taxType:settings.inspection.taxType,deductionOnFormalOrder:settings.inspection.deduction})}if(appState.step===6&&appState.draft.inspectionFee.agreed&&!appState.draft.inspectionFee.agreedAt)appState.draft.inspectionFee.agreedAt=new Date().toISOString();if(appState.step===7){saveCase();return}appState.step++;render();draftSaved()}
function showErrors(errors){document.querySelectorAll('.error').forEach(x=>x.hidden=true);let first=null;for(const [key,msg] of Object.entries(errors)){const id=key.includes('.')?key.split('.').at(-1):key;const p=document.querySelector(`#error-${CSS.escape(key)},#error-${CSS.escape(id)}`);const input=document.querySelector(`[name="${CSS.escape(key)}"],#${CSS.escape(key)}`);if(p){p.textContent=msg;p.hidden=false}(input||p?.parentElement)?.classList.add('has-error');if(input)input.classList.add('is-invalid');first??=input||p}first?.scrollIntoView({behavior:'smooth',block:'center'});first?.focus?.();toast('入力内容を確認してください。')}
function saveCase(){const now=new Date().toISOString(),d=clone(appState.draft);d.id=appState.editingId||d.id||uid();d.createdAt=appState.editingId?(cases.find(c=>c.id===appState.editingId)?.createdAt||now):now;d.updatedAt=now;d.media={count:appState.mediaFiles.length||d.media.count,saved:false,names:appState.mediaFiles.map(x=>x.file.name)};const idx=cases.findIndex(c=>c.id===d.id);if(idx>=0)cases[idx]=d;else cases.unshift(d);try{storage.saveCases(cases);storage.clearDraft()}catch(e){toast(e.message);return}appState.draft=d;appState.editingId=null;appState.step=8;render()}
function addMedia(files){const allowed=['image/jpeg','image/png','image/webp','video/mp4','video/quicktime'],max=20*1024*1024;let error='';for(const file of files){if(appState.mediaFiles.length>=3){error='添付できるのは最大3点です。';break}if(!allowed.includes(file.type)){error=`「${file.name}」は対応していない形式です。`;continue}if(file.size>max){error=`「${file.name}」は20MBを超えています。`;continue}appState.mediaFiles.push({file,url:URL.createObjectURL(file),type:file.type})}appState.draft.media.count=appState.mediaFiles.length;if(error)toast(error);render();draftSaved()}
function removeMedia(i){const x=appState.mediaFiles.splice(i,1)[0];if(x)URL.revokeObjectURL(x.url);appState.draft.media.count=appState.mediaFiles.length;render();draftSaved()}
function clearMedia(){if(!confirm('添付した写真・動画をすべて削除しますか？'))return;appState.mediaFiles.forEach(x=>URL.revokeObjectURL(x.url));appState.mediaFiles=[];appState.draft.media.count=0;render();draftSaved()}
async function doCopy(c){try{await copyText(caseText(c,settings));toast('相談内容をコピーしました。')}catch{toast('コピーできませんでした。端末の権限を確認してください。')}}
function sendEmail(c){try{location.href=buildMailto(c,settings)}catch(e){toast(e.message)}}
async function shareMedia(c){const files=appState.mediaFiles.map(x=>x.file);if(!files.length){toast('共有できる写真・動画がありません。再度選択してください。');return}if(!navigator.share||!navigator.canShare?.({files})){toast('この端末ではファイル共有を利用できません。メール画面で添付してください。');return}try{await navigator.share({title:'排煙窓事前チェック',text:`送信先：${settings.company.email}\n\n${caseText(c,settings)}`,files})}catch(e){if(e?.name!=='AbortError')toast('共有画面を開けませんでした。')}}
async function caseAction(action,id){const c=cases.find(x=>x.id===id);if(!c)return;if(action==='detail'){appState.draft=clone(c);appState.screen='detail';render()}if(action==='edit')start(clone(c));if(action==='copy')await doCopy(c);if(action==='duplicate'){const n=clone(c);n.id=uid();n.createdAt=n.updatedAt=new Date().toISOString();n.customer.contactName=`${n.customer.contactName}（複製）`;cases.unshift(n);storage.saveCases(cases);render();toast('相談内容を複製しました。')}if(action==='print'){appState.draft=clone(c);appState.screen='detail';render();printCurrentView()}if(action==='delete'){if(confirm('この相談内容を削除しますか？この操作は元に戻せません。')){cases=cases.filter(x=>x.id!==id);storage.saveCases(cases);render();toast('削除しました。')}}if(action==='status')changeStatus(c)}
function changeStatus(c){const options=Object.entries(LABELS.status).map(([v,l])=>`<option value="${v}" ${c.status===v?'selected':''}>${l}</option>`).join('');showModal('対応状況を変更',`<div class="field"><label for="statusSelect">対応状況</label><select id="statusSelect">${options}</select></div><div class="field"><label for="caseMemo">社内メモ</label><textarea id="caseMemo"></textarea></div>`,()=>{c.status=document.querySelector('#statusSelect').value;c.memo=document.querySelector('#caseMemo').value;storage.saveCases(cases);closeModal();render();toast('対応状況を更新しました。')},c.memo)}
function exportBackup(){download(`排煙窓相談_保存データ_${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({version:1,exportedAt:new Date().toISOString(),cases},null,2));toast('保存データをダウンロードフォルダへ書き出しました。')}
async function importBackup(file){if(!file)return;try{const data=JSON.parse(await file.text());if(!validBackup(data))throw new Error();if(!confirm(`${data.cases.length}件の相談をこの端末へ戻します。現在の履歴へ追加してよろしいですか？`))return;const map=new Map([...cases,...data.cases.map(normalizeCase)].map(c=>[c.id,c]));cases=[...map.values()];storage.saveCases(cases);render();toast('保存ファイルから相談内容を戻しました。')}catch{toast('このアプリで書き出した保存データファイルではありません。')}}
function deleteAll(){if(confirm('保存した相談をすべて削除しますか？この操作は元に戻せません。')){cases=[];storage.saveCases(cases);render();toast('すべて削除しました。')}}
async function saveSettings(){const form=document.querySelector('#settingsForm'),newCode=document.querySelector('#newSettingsPasscode')?.value.trim()||'',confirmation=document.querySelector('#confirmSettingsPasscode')?.value.trim()||'';if(newCode){if(!/^\d{4,8}$/.test(newCode)){toast('新しいパスコードは4〜8桁の数字で入力してください。');document.querySelector('#newSettingsPasscode').focus();return}if(newCode!==confirmation){toast('新しいパスコードが一致しません。');document.querySelector('#confirmSettingsPasscode').focus();return}}const nextSettings=settingsFromForm(form,settings);if(newCode)nextSettings.security.settingsPasscodeHash=await hashPasscode(newCode);settings=nextSettings;try{storage.saveSettings(settings);applySettings();renderHomeScreen();toast('業者設定を保存しました。')}catch(e){toast(e.message)}}
function loadLogo(file){if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>1024*1024){toast('ロゴはPNG・JPEG・WebP形式、1MB以下にしてください。');return}const reader=new FileReader();reader.onload=()=>{settings.company.logoDataUrl=String(reader.result);toast('ロゴを読み込みました。設定を保存してください。')};reader.readAsDataURL(file)}
function resetAllSettings(){if(confirm('会社情報、料金、表示設定を初期値へ戻しますか？')){settings=resetSettings();storage.resetSettings();render();toast('初期設定に戻しました。')}}
function enhanceSettings(){const form=document.querySelector('#settingsForm');const first=form?.querySelector('.card');if(!form||!first)return;const logo=document.createElement('div');logo.className='field';logo.innerHTML='<label for="companyLogo">ロゴ画像</label><input id="companyLogo" type="file" accept="image/png,image/jpeg,image/webp"><p class="hint">PNG・JPEG・WebP形式、1MB以下</p>';first.append(logo);const card=document.createElement('div');card.className='card stack';const title=document.createElement('h2');title.textContent='詳細料金・訪問条件';card.append(title);const entries=[['キャンセル時の説明','inspection.cancellation','text'],['不在時の説明','inspection.absence','text'],['複数症状の追加確認費','pricing.additionalSymptomFee','number'],['ワイヤー交換 最低額','pricing.symptoms.wire.0','number'],['ワイヤー交換 最高額','pricing.symptoms.wire.1','number'],['ハンドル交換 最低額','pricing.symptoms.spins.0','number'],['ハンドル交換 最高額','pricing.symptoms.spins.1','number'],['オペレーター交換 最低額','pricing.symptoms.wontOpen.0','number'],['オペレーター交換 最高額','pricing.symptoms.wontOpen.1','number'],['調整作業 最低額','pricing.symptoms.heavy.0','number'],['調整作業 最高額','pricing.symptoms.heavy.1','number'],['その他作業 最低額','pricing.symptoms.other.0','number'],['その他作業 最高額','pricing.symptoms.other.1','number']];for(const [label,name,type] of entries){const wrap=document.createElement('div');wrap.className='field';const lab=document.createElement('label');lab.htmlFor=name;lab.textContent=label;const input=document.createElement('input');input.id=input.name=name;input.type=type;input.value=name.split('.').reduce((o,k)=>o?.[k],settings)??'';wrap.append(lab,input);card.append(wrap)}form.insertBefore(card,form.lastElementChild);const security=document.createElement('div');security.className='card stack';security.innerHTML='<h2>業者設定のパスコード</h2><p class="hint">次回から設定画面を開くときに使用します。4〜8桁の数字を設定してください。空欄の場合は変更しません。</p><div class="field"><label for="newSettingsPasscode">新しいパスコード</label><input id="newSettingsPasscode" type="password" inputmode="numeric" maxlength="8" autocomplete="new-password"></div><div class="field"><label for="confirmSettingsPasscode">新しいパスコード（確認）</label><input id="confirmSettingsPasscode" type="password" inputmode="numeric" maxlength="8" autocomplete="new-password"></div>';form.insertBefore(security,form.lastElementChild)}

function normalizeCase(value){const c=value&&typeof value==='object'?value:createDraft();c.diagnosis??=createDraft().diagnosis;if(!Array.isArray(c.diagnosis.symptoms))c.diagnosis.symptoms=c.diagnosis.symptom?[c.diagnosis.symptom]:[];c.diagnosis.symptoms=[...new Set(c.diagnosis.symptoms.filter(key=>typeof key==='string'))];c.diagnosis.symptom=c.diagnosis.symptoms[0]||c.diagnosis.symptom||'';return c}

function requestSettingsAccess(){showModal('業者設定を開く','<p>この画面は排煙窓会社の担当者専用です。</p><div class="field"><label for="settingsPasscode">パスコード</label><input id="settingsPasscode" type="password" inputmode="numeric" maxlength="8" autocomplete="current-password"><p class="error" id="passcodeError" hidden></p></div>',verifySettingsPasscode);const save=document.querySelector('#modalSave');save.textContent='確認して開く';document.querySelector('#settingsPasscode').focus()}
async function verifySettingsPasscode(){const input=document.querySelector('#settingsPasscode'),error=document.querySelector('#passcodeError');if(!(await verifyPasscode(input.value,settings.security.settingsPasscodeHash))){error.textContent='パスコードが違います。';error.hidden=false;input.classList.add('is-invalid');input.select();return}closeModal();appState.screen='settings';render()}

function printCurrentView(){const previousTitle=document.title;const customer=appState.draft?.customer;document.title=`排煙窓事前チェック_${customer?.companyName||customer?.storeName||customer?.facilityName||customer?.contactName||'相談内容'}`;const restore=()=>{document.title=previousTitle;document.body.classList.remove('is-printing')};document.body.classList.add('is-printing');try{window.print();restore();setTimeout(()=>toast('印刷画面が開かない場合は、ブラウザのメニューから「印刷」または「プリント」を選択してください。'),100)}catch{restore();toast('印刷画面を開けませんでした。ブラウザのメニューから「印刷」または「プリント」を選択してください。')}}
function showHelp(){showModal('使い方',`<ol><li>依頼者情報と現場住所を入力します。</li><li>症状を選び、必要に応じて写真や動画を添付します。</li><li>質問に答えると修理費用の目安が表示されます。</li><li>現地調査費の条件を確認し、相談内容を保存します。</li></ol><p>写真・動画はこの端末にもサーバーにも保存されません。</p>`)}
function showModal(title,body,onSave=null,memo=''){document.querySelector('#modalRoot').innerHTML=`<div class="modal-backdrop" role="presentation"><div class="modal" role="dialog" aria-modal="true" aria-labelledby="modalTitle"><h2 id="modalTitle"></h2><div id="modalBody"></div><div class="modal-actions section">${onSave?'<button class="button" id="modalSave">保存</button>':''}<button class="button secondary" id="modalClose">閉じる</button></div></div></div>`;document.querySelector('#modalTitle').textContent=title;document.querySelector('#modalBody').innerHTML=body;if(document.querySelector('#caseMemo'))document.querySelector('#caseMemo').value=memo;document.querySelector('#modalClose').onclick=closeModal;if(onSave)document.querySelector('#modalSave').onclick=onSave;document.querySelector('#modalClose').focus()}
function closeModal(){document.querySelector('#modalRoot').innerHTML=''}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.hidden=false;clearTimeout(toast.id);toast.id=setTimeout(()=>t.hidden=true,3200)}
