import {loadVendorSubscription,readTenantId,updateVendorSubscription} from './cloudflare-platform.js?v=20260812j';
const tenantId=readTenantId(location.href),main=document.querySelector('#contractMain'),back=document.querySelector('#backLink');if(tenantId)back.href=`/?t=${encodeURIComponent(tenantId)}&admin=1`;initialize();
async function initialize(){if(!tenantId){renderError('契約先を確認できません','業者設定画面から開いてください。');return}try{const result=await loadVendorSubscription(tenantId);render(result)}catch(error){if(['identity_required','authentication_required'].includes(error.code)){location.href=`/?t=${encodeURIComponent(tenantId)}&admin=1`;return}renderError('契約情報を確認できません',error.message)}}
function render({subscription,plans,versions}){const current=['active','trialing','past_due'].includes(subscription.status),ended=['canceled','unpaid','incomplete_expired'].includes(subscription.status),selected=subscription.planCode||'monthly',checkout=new URL(location.href).searchParams.get('checkout');main.innerHTML=`<section class="contract-hero"><p class="eyebrow">1契約・1事業者アカウント</p><h1>契約・お支払い管理</h1><p>会社代表メールと共通パスコードで利用します。複数の担当者登録はありません。</p>${checkout==='success'?'<p class="contract-notice success">申込を受け付けました。決済確認後、契約状態が自動更新されます。</p>':checkout==='cancel'?'<p class="contract-notice">申込は完了していません。料金は発生していません。</p>':''}</section>${statusCard(subscription,current)}${current?portalCard(subscription):checkoutForm(plans,selected,versions,ended)}<section class="contract-rules"><h2>契約条件</h2><dl><div><dt>更新</dt><dd>月額または年額で自動更新</dd></div><div><dt>解約</dt><dd>いつでも手続き可能。現在の契約期間末日に終了</dd></div><div><dt>返金</dt><dd>契約期間途中の日割り返金なし</dd></div><div><dt>支払失敗</dt><dd>7日間の支払猶予後、未解決の場合は利用停止</dd></div><div><dt>再契約</dt><dd>契約終了後、同じ会社用URLと設定で再申込可能</dd></div></dl><p class="legal-links"><a href="terms.html" target="_blank">利用規約</a><a href="privacy.html" target="_blank">プライバシーポリシー</a><a href="commerce.html" target="_blank">特定商取引法に基づく表記</a></p></section>`;document.querySelector('#contractForm')?.addEventListener('submit',event=>startCheckout(event,versions));document.querySelector('#portalButton')?.addEventListener('click',openPortal)}
function statusCard(value,current){const labels={none:'未契約',checkout_pending:'申込処理中',trialing:'契約中',active:'契約中',past_due:'支払確認中',unpaid:'利用停止',canceled:'解約済み',incomplete:'申込未完了',incomplete_expired:'申込期限切れ',paused:'一時停止'};return `<section class="contract-status card"><div><p class="eyebrow">現在の状態</p><h2>${escape(labels[value.status]||value.status)}</h2><p>${value.planName?escape(value.planName):'料金プラン未選択'}${value.currentPeriodEnd?` ／ ${value.cancelAtPeriodEnd?'利用終了':'次回更新'}：${date(value.currentPeriodEnd)}`:''}</p></div>${value.status==='past_due'?`<p class="contract-alert">支払方法の更新が必要です。猶予期限：${date(value.graceEndsAt)}</p>`:value.cancelAtPeriodEnd?'<p class="contract-notice">解約予約済みです。契約期間末日まで利用できます。</p>':current?'<p class="success">サービスを利用できます。</p>':''}</section>`}
function portalCard(subscription){return `<section class="card contract-action"><h2>支払方法・解約を管理</h2><p>カード変更、請求履歴の確認、解約手続きはStripeの安全な契約管理画面で行います。</p><button class="button" id="portalButton" type="button">契約管理画面を開く</button><p class="hint">解約しても、現在の契約期間末日までは利用できます。</p></section>`}
function checkoutForm(plans,selected,versions,ended){return `<form id="contractForm" class="contract-checkout card"><div><p class="eyebrow">${ended?'再契約':'本番利用申込'}</p><h2>料金プランを選択</h2></div><div class="plan-grid">${plans.map(plan=>`<label class="plan-card"><input type="radio" name="planCode" value="${plan.code}" ${plan.code===selected?'checked':''}><span>${plan.discountLabel?`<em class="plan-discount">${escape(plan.discountLabel)}</em>`:''}<strong>${escape(plan.name)}</strong><b>税込 ${yen(plan.amountYen)}</b>${plan.monthlyEquivalentYen?`<small>月額換算 ${yen(plan.monthlyEquivalentYen)}</small>`:''}<small>${plan.interval==='month'?'1か月ごと':'1年ごと'}に自動更新</small></span></label>`).join('')}</div><section class="final-confirm"><h3>申込最終確認</h3><ul><li>初期費用：0円</li><li>解約手数料：0円</li><li>最低利用期間：なし</li><li>申込完了後、選択した周期で自動更新</li><li>解約は契約管理画面から行い、期間末日に終了</li><li>期間途中の日割り返金はありません</li></ul></section><label class="agreement"><input name="agreement" type="checkbox" required><span><a href="terms.html" target="_blank">利用規約</a>、<a href="privacy.html" target="_blank">プライバシーポリシー</a>、<a href="commerce.html" target="_blank">特定商取引法に基づく表記</a>を確認し、定期購入に同意します。</span></label><p class="error" id="contractError" hidden></p><button class="button" id="checkoutButton" type="submit">Stripeで申込・支払いへ進む</button><p class="hint">決済情報はStripeが管理し、このアプリにはカード番号を保存しません。規約版：${escape(versions.terms)}</p></form>`}
async function startCheckout(event,versions){event.preventDefault();const button=document.querySelector('#checkoutButton'),error=document.querySelector('#contractError'),planCode=new FormData(event.currentTarget).get('planCode');button.disabled=true;error.hidden=true;try{const result=await updateVendorSubscription(tenantId,{action:'checkout',planCode,agreements:{terms:true,privacy:true,commerce:true},versions});location.href=result.url}catch(caught){error.textContent=caught.message;error.hidden=false;button.disabled=false}}
async function openPortal(){const button=document.querySelector('#portalButton');button.disabled=true;try{const result=await updateVendorSubscription(tenantId,{action:'portal'});location.href=result.url}catch(caught){renderError('契約管理画面を開けません',caught.message)}}
function renderError(title,message){main.innerHTML=`<section class="card empty-state"><h1>${escape(title)}</h1><p>${escape(message)}</p><p><a href="${back.href}">業者設定へ戻る</a></p></section>`}
function yen(value){return `${Number(value).toLocaleString('ja-JP')}円`}function date(value){if(!value)return '未定';return new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'long',day:'numeric'}).format(new Date(value))}function escape(value){return String(value||'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
