import {database} from '../../_lib/db.js';
import {addGrace,stripeTimestamp} from '../../_lib/billing.js';
import {verifyStripeWebhook} from '../../_lib/stripe.js';
import {error,json} from '../../_lib/http.js';

export async function onRequestPost({request,env}){
  const raw=await request.text();if(!(await verifyStripeWebhook(raw,request.headers.get('stripe-signature'),String(env.STRIPE_WEBHOOK_SECRET||''))))return error(400,'invalid_signature','署名を確認できません。');
  let event;try{event=JSON.parse(raw)}catch{return error(400,'invalid_event','イベントを読み取れません。')}
  const db=database(env),now=new Date().toISOString(),existing=await db.prepare('SELECT event_id FROM billing_webhook_events WHERE event_id=?1').bind(event.id).first();if(existing)return json({ok:true,deduplicated:true});
  await db.prepare("INSERT INTO billing_webhook_events (event_id,event_type,status,received_at) VALUES (?1,?2,'processing',?3)").bind(event.id,event.type,now).run();
  try{const object=event.data?.object||{},tenantId=await resolveTenant(db,object);if(!tenantId){await finish(db,event.id,'ignored',null,'tenant_not_found');return json({ok:true,ignored:true})}await applyEvent(db,event.type,object,tenantId,now);await finish(db,event.id,'processed',tenantId,'');return json({ok:true})}catch(caught){console.error(caught);await finish(db,event.id,'failed',null,String(caught?.message||'processing_failed').slice(0,500));return error(500,'webhook_failed','イベント処理に失敗しました。')}
}
async function resolveTenant(db,object){const direct=object.metadata?.tenant_id||object.client_reference_id;if(direct)return String(direct);const customer=typeof object.customer==='string'?object.customer:object.customer?.id,subscription=typeof object.subscription==='string'?object.subscription:object.subscription?.id;if(!customer&&!subscription)return null;const row=await db.prepare('SELECT tenant_id FROM billing_subscriptions WHERE provider_customer_id=?1 OR provider_subscription_id=?2 LIMIT 1').bind(customer||'',subscription||'').first();return row?.tenant_id||null}
async function applyEvent(db,type,object,tenantId,now){
  if(type==='checkout.session.completed'){await db.prepare("UPDATE billing_subscriptions SET provider_customer_id=?1,provider_subscription_id=?2,status='active',updated_at=?3 WHERE tenant_id=?4").bind(object.customer||null,object.subscription||null,now,tenantId).run();return}
  if(type.startsWith('customer.subscription.')){const status=normalizeStatus(object.status),start=stripeTimestamp(object.current_period_start),end=stripeTimestamp(object.current_period_end),canceled=stripeTimestamp(object.canceled_at),ended=stripeTimestamp(object.ended_at),grace=status==='past_due'?addGrace(now):null;await db.prepare("INSERT INTO billing_subscriptions (tenant_id,provider,provider_customer_id,provider_subscription_id,plan_code,status,cancel_at_period_end,current_period_start,current_period_end,grace_ends_at,canceled_at,ended_at,created_at,updated_at) VALUES (?1,'stripe',?2,?3,'',?4,?5,?6,?7,?8,?9,?10,?11,?11) ON CONFLICT(tenant_id) DO UPDATE SET provider_customer_id=excluded.provider_customer_id,provider_subscription_id=excluded.provider_subscription_id,status=excluded.status,cancel_at_period_end=excluded.cancel_at_period_end,current_period_start=excluded.current_period_start,current_period_end=excluded.current_period_end,grace_ends_at=excluded.grace_ends_at,canceled_at=excluded.canceled_at,ended_at=excluded.ended_at,updated_at=excluded.updated_at").bind(tenantId,object.customer||null,object.id||null,status,object.cancel_at_period_end?1:0,start,end,grace,canceled,ended,now).run();await syncTenant(db,tenantId,status,end,grace,now);return}
  if(type==='invoice.payment_failed'){const grace=addGrace(now);await db.prepare("UPDATE billing_subscriptions SET status='past_due',grace_ends_at=?1,last_payment_error='お支払いを確認できません。支払方法を更新してください。',updated_at=?2 WHERE tenant_id=?3").bind(grace,now,tenantId).run();await db.prepare("UPDATE tenants SET license_type='production',status='active',expires_at=?1,updated_at=?2 WHERE id=?3").bind(grace,now,tenantId).run();return}
  if(type==='invoice.paid'){await db.prepare("UPDATE billing_subscriptions SET status='active',grace_ends_at=NULL,last_payment_error='',updated_at=?1 WHERE tenant_id=?2").bind(now,tenantId).run()}
}
async function syncTenant(db,tenantId,status,periodEnd,grace,now){if(['active','trialing'].includes(status)){await db.prepare("UPDATE tenants SET license_type='production',status='active',expires_at=COALESCE(?1,expires_at),updated_at=?2 WHERE id=?3").bind(periodEnd,now,tenantId).run();return}if(status==='past_due'){await db.prepare("UPDATE tenants SET license_type='production',status='active',expires_at=?1,updated_at=?2 WHERE id=?3").bind(grace||addGrace(now),now,tenantId).run();return}const end=periodEnd&&new Date(periodEnd)>new Date(now)?periodEnd:null;await db.prepare("UPDATE tenants SET license_type='production',status=?1,expires_at=COALESCE(?2,expires_at),updated_at=?3 WHERE id=?4").bind(end?'active':'suspended',end,now,tenantId).run()}
function normalizeStatus(value){return ['trialing','active','past_due','unpaid','canceled','incomplete','incomplete_expired','paused'].includes(value)?value:'incomplete'}
async function finish(db,id,status,tenant,errorMessage){await db.prepare('UPDATE billing_webhook_events SET status=?1,tenant_id=?2,error_message=?3,processed_at=?4 WHERE event_id=?5').bind(status,tenant,errorMessage,new Date().toISOString(),id).run()}
